### ISSUE TITLE
DRY the CacheString

### ISSUE THREAD

**Issue by Wicpar** [paulocsanz/arraystring#5]
there is a lot of redundant code in the CacheString

we could use [delegate](https://docs.rs/delegate/latest/delegate/) to do some of that, or other means.

**Comment by Wicpar** [comment]
with some testing only teh cache string makes sense, an ArrayString<7> is already optimized down to a register

**Comment by paulocsanz** [comment]
I was able to remove most implementations for CacheString on main because of Deref and DerefMut provided for it based on ArrayString.

Sadly functions that return Self or trait implementations can't be done, but honestly now the overlap is so small that I'm ok with it. I'm still open to changing that, but closing this for now as things have changed a lot.

I'm not eager to use a lot of syntax magic to avoid this small problem but I'm open to it provided you can show me a reasonable approach

**Comment by Wicpar** [comment]
yes it looks quite reasonable now
